# Generated by Django 5.2 on 2025-05-05 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "request_type",
                    models.CharField(
                        choices=[
                            ("wish", "Пожелание"),
                            ("issue", "Проблема"),
                            ("claim", "Претензия"),
                            ("other", "Другое"),
                        ],
                        verbose_name="Тип обращения",
                    ),
                ),
                ("full_text", models.TextField(verbose_name="Текст обращения")),
                (
                    "file",
                    models.FileField(
                        blank=True, null=True, upload_to="", verbose_name="Файл"
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата обращения"
                    ),
                ),
            ],
            options={
                "verbose_name": "Обращение",
                "verbose_name_plural": "Обращения",
                "ordering": ["-date"],
            },
        ),
    ]
