# Generated by Django 5.2 on 2025-05-05 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='theme',
            field=models.CharField(blank=True, verbose_name='Тема обращения'),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='feedback/', verbose_name='Файл'),
        ),
    ]
